name: Build SDR DVB-T2 (Windows)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "5.15.2"
          host: "windows"
          target: "desktop"
          arch: "win64_msvc2019_64"

      - name: Configure (DISABLE AVX2)
        shell: cmd
        run: |
          mkdir build
          cd build
          qmake ..\src\sdr_receiver_dvb_t2_v2.pro CONFIG+=release DEFINES+=CI_BUILD

      - name: Build
        shell: cmd
        run: |
          cd build
          nmake

      - name: Package
        shell: cmd
        run: |
          mkdir output
          copy build\bin\sdr_receiver_dvb_t2_v2.exe output\

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: sdr_receiver_dvb_t2
          path: output/
